# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric (https://fabricmc.net/develop)
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod
version=1.0.0
group=com.betterflying
archives_base_name=better-flying

# Optional integrations
fabric_api_version=0.155.3+26.1.2
modmenu_version=18.0.1
yacl_version=3.9.6+26.1-fabric
